### PR TITLE
Add Vani Rao as notaryproject maintainer

### PR DESCRIPTION
**Pull request by vaninrao10**
Add Vani Rao as a seed maintainer of notaryproject based on their activity and as per - https://github.com/notaryproject/notaryproject/issues/224

Signed-off-by: vaninrao10 <111005862+vaninrao10@users.noreply.github.com>

### CODE REVIEW

**Review by priteshbandi — APPROVED** [review]
LGTM but IANAM

**Review by toddysm — APPROVED** [review]
LGTM but IANAM

**Review by SteveLasker — APPROVED** [review]
LGTM

**Review by FeynmanZhou — APPROVED** [review]
LGTM but IANAM

**Review by yizha1 — APPROVED** [review]
LGTM but IANAM

**Review by gokarnm — APPROVED** [review]
LGTM but IANAM

**Review by iamsamirzon — APPROVED** [review]

**Comment by yizha1** [comment]
Close as aggregated PR https://github.com/notaryproject/notaryproject/pull/240 was merged.

**Pull request closed without merging**
