### PR TITLE
Support for JWT and COSE envelopes

### PR DESCRIPTION
**Pull request by SteveLasker**
- Incorporates feedback from #139
- Splits the envelope formats to separate files

Signed-off-by: Steve Lasker <stevenlasker@hotmail.com>

### CODE REVIEW

**Comment by SteveLasker** [comment]
@shizhMSFT, @briankr-ms, @roywill, @letmaik, @gokarnm from PR #139

**Comment by SteveLasker** [comment]
A self note to update the specs to incorporate the annotation over blob storage issue: #123

**Review by gokarnm — APPROVED** [review]

**Comment by gokarnm** [comment]
LGTM! Thanks for the changes and separating the envelopes out. This is good for me to iterate on.

**Comment by SteveLasker** [comment]
Merging into cose-envelope for additional changes.

**Comment by dtzar** [comment]
https://github.com/notaryproject/notation-core-go/pull/7

**Pull request merged**
