### PR TITLE
COSE updates...again

### PR DESCRIPTION
**Pull request by letmaik**
This supersedes https://github.com/notaryproject/notaryproject/pull/179.

@SteveLasker Don't squash merge. When `cose-envelope` is merged into `main` at some point, then we can squash merge, but all PRs into `cose-envelope` must have merge commits to avoid conflicts.

https://github.com/notaryproject/notaryproject/compare/main..letmaik:notaryproject:letmaik/cose-envelope-patches2

### CODE REVIEW

**Comment by dtzar** [comment]
The problem again @letmaik is the DCO issue.  Shiwei squash merged and gave attribution.  If you go as-is then each person needs to fix their issues.

**Comment by letmaik** [comment]
Oh dear... well, I fixed some of the DCO issues (my commits plus the latest from Brian, by doing a force push via Steve to get rid of that one) but I didn't realize the branch was full of them. Well, this is not fixable from a PR then, since a PR cannot correct existing commits. 
I'm tempted to just abandon that branch completely and create a single new commit on top of main in a new branch, with a bunch of Co-authored-by.

**Comment by dtzar** [comment]
@letmaik - can we just merge Shiwei's and then you do another PR on top of that for what you think needs to be different?

**Comment by letmaik** [comment]
@dtzar That won't work. There are existing commits in that branch that have the wrong Signed-off-by. You can't fix that through PRs. That requires force-pushing on that branch.

**Comment by dtzar** [comment]
Yes, this is why Shiwei did the attribution trick recommended by Sajay.

**Comment by letmaik** [comment]
I don't really understand how that should help, but I'm closing this PR now as it's not what we want.

**Pull request closed without merging**
