### PR TITLE
Update COSE spec

### PR DESCRIPTION
**Pull request by shizhMSFT**
Changes:
- Merge the latest changes from `main` branch
- Update COSE spec
- Add COSE support to the plugin spec

See also [comparing with `main`](https://github.com/notaryproject/notaryproject/compare/main..shizhMSFT:notaryproject:cose-envelope).

### CODE REVIEW

**Comment by shizhMSFT** [comment]
Note: The DCO check is failed due to

> Commit sha: [a99fd70](https://github.com/notaryproject/notaryproject/pull/179/commits/a99fd700f03c51ab7d7e0ad30a681b5c1389544d), Author: Pritesh Bandi, Committer: GitHub; Expected "Pritesh Bandi [priteshbandi@gmail.com](mailto:priteshbandi@gmail.com)", but got "Pritesh Bandi [pritesb@amazon.com](mailto:pritesb@amazon.com)".
> Commit sha: [80ec795](https://github.com/notaryproject/notaryproject/pull/179/commits/80ec795efdd4e68b8294be5dabd42502020ef123), Author: Quim Muntal, Committer: GitHub; Expected "Quim Muntal [quimmuntal@gmail.com](mailto:quimmuntal@gmail.com)", but got "qmuntal [qmuntaldiaz@microsoft.com](mailto:qmuntaldiaz@microsoft.com)".
> Commit sha: [2d3c8dd](https://github.com/notaryproject/notaryproject/pull/179/commits/2d3c8ddd9e8a1f6bf7feb1cac7228b05b0ec9ed7), Author: Quim Muntal, Committer: GitHub; Expected "Quim Muntal [qmuntaldiaz@microsoft.com](mailto:qmuntaldiaz@microsoft.com)", but got "qmuntal [qmuntaldiaz@microsoft.com](mailto:qmuntaldiaz@microsoft.com)".
> Commit sha: [278977e](https://github.com/notaryproject/notaryproject/pull/179/commits/278977e3a433884042a90ce9d89fc0ed294a4376), Author: Sajay Antony, Committer: GitHub; Expected "Sajay Antony [1821104+sajayantony@users.noreply.github.com](mailto:1821104+sajayantony@users.noreply.github.com)", but got "Sajay Antony [sajaya@microsoft.com](mailto:sajaya@microsoft.com)".

**Comment by dtzar** [comment]
@qmuntal @sajayantony @priteshbandi - can you please fix the DCO errors?

**Comment by SteveLasker** [comment]
Looks like the DCO errors have expanded. Can we squash these and sign within the code-envelope branch?

**Comment by sajayantony** [comment]
@shizhMSFT as discussed on the call - please squash and ensure attribution to all contributors in the commit.

**Comment by sajayantony** [comment]
@shizhMSFT - can you attribute all authors since its a squash commit in the commit message - something similar to - 
https://github.com/opencontainers/distribution-spec/commit/12ffe009f98353c65b8c5f10d771b4999b0a3d16

**Comment by shizhMSFT** [comment]
> @shizhMSFT - can you attribute all authors since its a squash commit in the commit message - something similar to - [opencontainers/distribution-spec@12ffe00](https://github.com/opencontainers/distribution-spec/commit/12ffe009f98353c65b8c5f10d771b4999b0a3d16)

@sajayantony Done!

**Comment by shizhMSFT** [comment]
The co-authors are determined by the compare result by GitHub. See https://github.com/notaryproject/notaryproject/compare/cose-envelope...shizhMSFT:cose-envelope-bak

**Comment by letmaik** [comment]
@shizhMSFT The PR isn't up to date with main, see the error in the comparison page: https://github.com/notaryproject/notaryproject/compare/main...shizhMSFT:notaryproject:cose-envelope Can you check?

**Comment by shizhMSFT** [comment]
@letmaik It's up to date with `main`. I just noticed that the GitHub comparison page shows [Merge Diff](https://github.com/notaryproject/notaryproject/compare/main...shizhMSFT:notaryproject:cose-envelope) instead of [Full Diff](https://github.com/notaryproject/notaryproject/compare/main..shizhMSFT:notaryproject:cose-envelope).

Please try two dots `..` instead of three dots `...` when comparing two branches.

**Comment by letmaik** [comment]
@shizhMSFT I'm not sure about that. I checked out your branch and then tried to merge in current `main` and I expected a no-op, but instead I got this:
> $ git merge main
Auto-merging specs/plugin-extensibility.md
CONFLICT (content): Merge conflict in specs/plugin-extensibility.md
Auto-merging signature-specification.md
CONFLICT (content): Merge conflict in signature-specification.md
Automatic merge failed; fix conflicts and then commit the result.

**Comment by shizhMSFT** [comment]
@letmaik If you run the command from your comment against the `cose-envelope` branch of this `notaryproject` repo, you will get the same conflict as follows.
```
$ git remote -v
origin  https://github.com/notaryproject/notaryproject.git (fetch)
origin  https://github.com/notaryproject/notaryproject.git (push)
$ git checkout cose-envelope 
Branch 'cose-envelope' set up to track remote branch 'cose-envelope' from 'origin'.
Switched to a new branch 'cose-envelope'
$ git merge main
Auto-merging specs/plugin-extensibility.md
CONFLICT (content): Merge conflict in specs/plugin-extensibility.md
Auto-merging signature-specification.md
CONFLICT (content): Merge conflict in signature-specification.mdAuto-merging signature-envelope-jws.md
CONFLICT (add/add): Merge conflict in signature-envelope-jws.md
Automatic merge failed; fix conflicts and then commit the result.
```

Since my change is based on the `cose-envelope` branch of this `notaryproject` repo, there is no way to merge to `main` without squashing.

**Comment by letmaik** [comment]
@shizhMSFT The conflicts against `main` is what I had resolved in https://github.com/notaryproject/notaryproject/pull/177, see also the fact that it is mergable with `main`: https://github.com/notaryproject/notaryproject/compare/main...letmaik:letmaik/cose-envelope-patches
I'm afraid this PR still needs a bit of git love.

**Comment by shizhMSFT** [comment]
As mentioned by https://github.com/notaryproject/notaryproject/pull/177#issuecomment-1202655355, #177 was mis-squash-and-merged and causes conflicts against `main`: https://github.com/notaryproject/notaryproject/compare/main...cose-envelope.

@letmaik @SteveLasker We need to fix the `notaryproject:cose-envelope` branch first 😢

**Comment by letmaik** [comment]
@SteveLasker Can you remove the last commit on cose-envelope (9ec640bc64003175449803436a52fb32037c5ddb)? Then @shizhMSFT can do a proper PR. Something like `git reset --hard HEAD~1` and `git push -f` should work.

**Comment by SteveLasker** [comment]
> @SteveLasker Can you remove the last commit on cose-envelope (https://github.com/notaryproject/notaryproject/commit/9ec640bc64003175449803436a52fb32037c5ddb)

Done

**Comment by letmaik** [comment]
@shizhMSFT Let's close this PR. See https://github.com/notaryproject/notaryproject/pull/180

**Comment by letmaik** [comment]
@dtzar and @sajayantony say this PR should fix the DCO issue. I'm happy to try it and then deal with the squash merge issue in a follow up PR. Can someone press the button?

**Review by dtzar — APPROVED** [review]

**Comment by dtzar** [comment]
Per the community call, we can go ahead and merge this since it isn't into the main branch it doesn't require the official code review processes.

**Pull request merged**
