### PR TITLE
Updates certificates keyusage and eku MUST NOT lists.

### PR DESCRIPTION
**Pull request by priteshbandi**
Updates certificates keyusage and eku MUST NOT lists.

### CODE REVIEW

**Comment by priteshbandi** [comment]
cc: @ianjmcm, @shizhMSFT

**Comment by SteveLasker** [comment]
Is this related to #167?

**Review by dtzar — APPROVED** [review]

**Comment by SteveLasker** [comment]
@priteshbandi, can you clarify if this is tied to #167

**Comment by priteshbandi** [comment]
> 

This PR is on top of #167

**Review by rgnote — APPROVED** [review]

**Review by gokarnm — APPROVED** [review]
LGTM!

**Review by NiazFK — APPROVED** [review]
LGTM

**Pull request merged**
