### PR TITLE
initial design options

### PR DESCRIPTION
**Pull request by samuelkarp**
This document is meant to capture a few different ideas around how to relate signatures to the objects we wish to sign.  This is meant as a discussion point, and not as a concrete proposal to use a particular approach (or even a recommendation).  This document is *not* exhaustive, and is meant as a companion to both @SteveLasker's [scenarios pull request][stevelasker-scenarios] and @justincormack's [signing overview][jc-signing-overview].

[jc-signing-overview]:   https://docs.google.com/document/d/1lffOYCDXBoxRumQre32yv1jUN2NfOkWugoDEJ_2DdEk/edit#
[stevelasker-scenarios]: https://github.com/notaryproject/requirements/pull/1

(This is a copy of https://github.com/notaryproject/requirements/pull/6, which was accidentally closed when the `master` branch was changed to `main`.)

### CODE REVIEW

**Comment by dlorenc** [comment]
Is this still relevant? It has a ton of great content. Should it be merged somewhere?

**Comment by samuelkarp** [comment]
I don't have permissions to merge it myself, but yes I had opened it with the idea that merging it would be useful.

**Comment by dlorenc** [comment]
> I don't have permissions to merge it myself, but yes I had opened it with the idea that merging it would be useful.

Who does have merge permissions in this org/repo?

**Comment by samuelkarp** [comment]
> Who does have merge permissions in this org/repo?

I think it's just @SteveLasker.

**Comment by SteveLasker** [comment]
As mentioned, we started with a few folks making progress and we didn't get all the processes in place.
We'll work to get that corrected as we need a scalable, and clear solution.

That said, when this and PR #6 were initially created, we hadn't outlined an approach for iterations and what to merge vs. keep as PRs. At the time, we decided to keep PRs open that we wanted to iterate upon.

As we made more progress and needed to commit stuff, we agreed on prototype branches, with each prototype having clear goals.

So, the question is what prototype would you like to merge this with?

**Comment by dlorenc** [comment]
Thanks @SteveLasker ! Getting that process in place will help.

My 2c: at present, this project is very confusing for newcomers. Stuff is spread across branches and forks and branches of forks, and everyone appears to be mostly working in isolation.

Some PRs (the demo scripts, the signature format, the changes to distribution) appear to go in with little to no discussion or time for feedback, while others sit around for months.

Clarifying this will help people understand what's going on currently, where the project is going, and how they can get involved.

**Comment by SteveLasker** [comment]
@dlorenc, agreed on having things spread. 
We did put together the Notary v2 status for folks to get a sense of where we're at, and where we're going.
- [Notary Project Overview](https://github.com/notaryproject/notaryproject#notary-project-overview)
- [Notary v2 February 2021 Status](https://github.com/notaryproject/notaryproject/blob/main/notary-status-2021-02.md)
- [Plans for 2021](https://github.com/notaryproject/notaryproject/blob/main/notary-status-2021-02.md#plans-for-2021)

**Comment by SteveLasker** [comment]
Repos cleanup has been captured here #51, which is mostly done.
> This is meant as a discussion point, and not as a concrete proposal 

@samuelkarp, can you please open a discussion with this content. GitHub enables moving of issues, but not PRs. This is great content we should capture.

**Comment by SteveLasker** [comment]
Thanks, @samuelkarp for the initial design discussions. 
Closing as an active issue

**Pull request closed without merging**
