### PR TITLE
Add Pritesh Bandi as notaryproject maintainer

### PR DESCRIPTION
**Pull request by vaninrao10**
Add Pritesh Bandi as a seed maintainer of notaryproject based on [their](https://github.com/notaryproject/notaryproject/commits?author=priteshbandi) activity as per - https://github.com/notaryproject/notaryproject/issues/224

Signed-off-by: vaninrao10 <111005862+vaninrao10@users.noreply.github.com>

### CODE REVIEW

**Review by yizha1 — APPROVED** [review]
LGTM but IANAM

**Comment by iamsamirzon** [comment]
LGTM but IANAM

**Review by toddysm — APPROVED** [review]
LGTM but IANAM

**Review by SteveLasker — APPROVED** [review]
LGTM

**Review by gokarnm — APPROVED** [review]
LGTM but IANAM

**Comment by iamsamirzon** [comment]
LGTM but IANAM

**Review by iamsamirzon — APPROVED** [review]

**Comment by yizha1** [comment]
Close as aggregated PR https://github.com/notaryproject/notaryproject/pull/240 was merged.

**Pull request closed without merging**
