### PR TITLE
chore: fix wrong file path for the Fuzzing security test report

### PR DESCRIPTION
**Pull request by FeynmanZhou**
fix wrong file path for the Fuzzing security test report

### CODE REVIEW

**Comment by AdamKorcz** [comment]
Missing the "fuzzing". Should be: `security/reports/fuzzing`

@FeynmanZhou

**Review by toddysm — DISMISSED** [review]

**Comment by FeynmanZhou** [comment]
> Missing the "fuzzing". Should be: `security/reports/fuzzing`
> 
> @FeynmanZhou

Resolved.

**Review by toddysm — APPROVED** [review]

**Review by vaninrao10 — APPROVED** [review]

**Review by NiazFK — APPROVED** [review]
LGTM

**Review by SteveLasker — APPROVED** [review]
LGTM

**Pull request merged**
