### PR TITLE
doc: add back mistakenly removed sentence

### LINKED ISSUE #274: Follow up the removal of unsigned attributes are typically signed by a third party
@yizha1 , is there a reason we removed this line 

`These attributes are typically signed by a third party (e.g. CA, TSA).`

_Originally posted by @gokarnm in https://github.com/notaryproject/specifications/pull/256#discussion_r1284974781_

### PR DESCRIPTION
**Pull request by yizha1**
Resolve #274 

Signed-off-by: Yi Zha <yizha1@microsoft.com>

### CODE REVIEW

**Review by ghost — APPROVED** [review]
LGTM

**Review by shizhMSFT — COMMENTED** [review]
> These attributes are typically signed by a third party (e.g. CA, TSA).

This sentence is misleading that readers may think unsigned attributes are counter signatures. However, they are not.

Again, unsigned attributes can be added or stripped without signers' notice even if they are signed by a 3rd party.

**Comment by yizha1** [comment]
@shizhMSFT  do you have any suggestions? In most cases (typically), the unsigned attributes contain attributes that are signed by CA or TSA.

**Review by shizhMSFT — COMMENTED** [review]
@yizha1 I'd suggest leaving it as it is now or considering
> These attributes may be independently signed by a third party (e.g. CA, TSA) for various purposes.

**Review by priteshbandi — APPROVED** [review]
LGTM

**Review by shizhMSFT — APPROVED** [review]
LGTM

**Review by toddysm — APPROVED** [review]

**Pull request merged**
